name: DevOps / PR Hygiene

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

concurrency:
  group: devops-pr-hygiene-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semantic-pr:
    permissions:
      contents: read
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-semantic-pr.yml@5dfbb4986ceb88f6518fa719da3a255294cf03cf # v1.0.3
    with:
      require-scope: false

  actionlint:
    permissions:
      contents: read
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-actionlint.yml@5dfbb4986ceb88f6518fa719da3a255294cf03cf # v1.0.3
    with:
      working-directory: "."
